export const types = {
    START_UPDATING_RESERVATIONS: 'START_UPDATING_RESERVATIONS',
    FINISH_UPDATING_RESERVATIONS: 'FINISH_UPDATING_RESERVATIONS',
    ERROR_UPDATING_RESERVATIONS: 'ERROR_UPDATING_RESERVATIONS',
    HANDLE_DIALOG: 'HANDLE_DIALOG',
    START_UPDATING_USERS: 'START_UPDATING_USERS',
    FINISH_UPDATING_USERS: 'FINISH_UPDATING_USERS',
    ERROR_UPDATING_USERS: 'ERROR_UPDATING_USERS',
};
